apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ printf "%s-git" (include "longshoreman.fullname" .) }}
    labels:
        {{- include "longshoreman.labels" . | nindent 8 }}
data:
    {{- with .Values.git.config }}
    config: {{ . }}
    {{- end }}
