apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ printf "%s-scripts" (include "longshoreman.fullname" .) }}
    labels:
        {{- include "longshoreman.labels" . | nindent 8 }}
binaryData:
    {{- range $path, $bytes := .Files.Glob "scripts/**" }}
        {{- $name := base $path }}
        {{- print $name | nindent 8 }}{{ print " : " }} {{ $.Files.Get $path | b64enc }}
    {{- end }}
