{{- if not .Values.aws.credentialsSecretName }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ printf "%s-aws-credentials" (include "longshoreman.fullname" .) }}
    labels:
        {{- include "longshoreman.labels" . | nindent 8 }}
type: opaque
data:
    {{- with .Values.aws }}
    {{- with .credentials }}
    credentials: {{ . }}
    {{- end }}
    {{- end }}
{{- end }}
