{{- if and (not .Values.ssh.keysSecretName) (not .Values.ssh.keys) }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ printf "%s-ssh-keys" (include "longshoreman.fullname" .) }}
    labels:
        {{- include "longshoreman.labels" . | nindent 8 }}
type: kubernetes.io/ssh-auth
data:
    {{- with .Values.ssh.keys }}
    {{- with .privateKey }}
    ssh-privatekey: {{ . }}
    {{- end }}
    {{- with .publicKey }}
    ssh-publickey: {{ . }}
    {{- end }}
    {{- end }}
{{- end }}
