apiVersion: v1
kind: Secret
metadata:
    name: {{ printf "%s-secret" (include "longshoreman.fullname" .) }}
    labels:
        {{- include "longshoreman.labels" . | nindent 8 }}
data:
    {{- range $path, $bytes := .Files.Glob (printf "$s/**" .Values.secretSourceDir) }}
        {{- $name := base $path }}
        {{- print $name | nindent 8 }}{{ print " : " }} {{ $.Files.Get $path | b64enc }}
    {{- end }}
