apiVersion: v1
kind: Service
metadata:
  name: {{ include "longshoreman.fullname" . }}
  labels:
    {{- include "longshoreman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2222
      protocol: TCP
      name: ssh
  selector:
    {{- include "longshoreman.selectorLabels" . | nindent 4 }}
