apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ printf "%s-ssh" (include "dev-container-workflow.fullname" .) }}
    labels:
        {{- include "dev-container-workflow.labels" . | nindent 8 }}
data:
    {{- with .Values.ssh }}
    {{- if .authorizedKeys }}
    authorized_keys: {{ .authorizedKeys }}
    {{- end }}
    {{- if .config }}
    config: {{ .config }}
    {{- end }}
    {{- end }}
