apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ printf "%s-aws" (include "dev-container-workflow.fullname" .) }}
    labels:
        {{- include "dev-container-workflow.labels" . | nindent 8 }}
data:
    config: {{ .Values.aws.config }}
