apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev-container-workflow.fullname" . }}
  labels:
    {{- include "dev-container-workflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.sshPort }}
      protocol: TCP
      name: ssh
  selector:
    {{- include "dev-container-workflow.selectorLabels" . | nindent 4 }}
