#!/bin/sh
# Written for alpine/git. Depends on curl, git, tar, and ssh (for ssh-keygen)
ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key
$SCRIPTS_VOLUME/volumes
$SCRIPTS_VOLUME/asdf
$SCRIPTS_VOLUME/krew
$SCRIPTS_VOLUME/ksops
$SCRIPTS_VOLUME/vim-configuration
$SCRIPTS_VOLUME/tmux-configuration
