#!/bin/sh
if ! [[ git -C $HOME/.vim rev-parse --is-inside-work-tree ]]; then
    git clone git@github.com:ClusterDaemon/vim.git --single-branch --branch "main"
else
    git checkout main --force
    git pull --force --autostash
fi
if ! [[ -L $HOME/.vimrc ]]; then
    if [[ -f $HOME/.vimrc ]]; then
        rm -f $HOME/.vimrc
    fi
    ln -S $HOME/.vim/.vimrc $HOME/.vimrc
fi
