# Override the name of this Helm chart within rendered manifests
nameOverride: ""
# Override the name of this Helm chart in addition to its release within rendered manifests
fullnameOverride: ""

user:
  # Define POSIX user name
  userName: "user"
  # Define POSIX user ID.
  uid: 1000
  primaryGroup: "user"
  gid: 1000
  # This is a password as it appears in /etc/shadow. If you are unsure of how it is generated, use `adduser` locally.
  # Setting a password will disable passwordless login.
  hashedPassword:

image:
  # Overrides the OCI registry from the cluster default
  registry:
  # Overrides the image/repository name
  repository: 
  # Overrides the image tag whose default is the chart appVersion.
  tag: 
  # By default use container image cache
  pullPolicy: "IfNotPresent"

imagePullSecrets: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

configSourceDir: "config"
secretSourceDir: "secret"

# Init container configuration. Must be able to read/write root fs as root.
init:
  SecurityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: false
  image:
    registry:
    # Defaults to chart name with a suffix of "-init"
    repository:
    tag:
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7681

resources:
  requests:
    cpu: 1
    memory: 1Gi

volume:
  accessMode:
  storageClass:
  request:

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
