#!/bin/sh
viaduct_dir="$HOME/.config/kustomize/plugin/viaduct.ai/v1"
if ! [[ -d $viaduct_dir ]]; then
    mkdir -p $viaduct_dir
fi
if ! [[ -f $viaduct_dir/ksops ]]; then
    curl -L "https://github.com/viaduct-ai/kustomize-sops/releases/download/v3.0.2/ksops_3.0.2_Linux_x86_64.tar.gz" \
        | tar -xz -C $viaduct_dir ksops
fi
