#!/bin/sh

# Validate volumes
if ! [[ -w $HOME ]]; then
    echo "ERROR: Home persistence volume not writable. Unable to configure user applications!"
    exit 1
fi
aws=1
if ! [[ -d $AWS_VOLUME ]]; then
    echo "WARN: AWS configuration volume not present. Unable to configure AWS CLI."
    aws=0
fi
git=1
if ! [[ -d $GIT_VOLUME ]]; then
    echo "WARN: GIT configuration volume not present. Unable to configure Git CLI."
    git=0
fi
ssh=1
if ! [[ -d $SSH_VOLUME ]]; then
    echo "WARN: SSH configuration volume not present. Unable to configure SSH client and authorized_users."
   ssh=0
fi

# Symlink configuration volumes
if [[ $aws == 1 ]]; then
    if ! [[ -L $HOME/.aws ]]; then
        if [[ -f $HOME/.aws ]]; then
            rm -rf $HOME/.aws
        fi
        ln -s $AWS_VOLUME $HOME/.aws
    fi
fi

if [[ $ssh == 1 ]]; then
    if ! [[ -L $HOME/.ssh ]]; then
        if [[ -f $HOME/.ssh ]]; then
            rm -rf $HOME/.ssh
        fi
        ln -s $SSH_VOLUME $HOME/.ssh
    fi
fi

if [[ $git == 1 ]]; then
    if ! [[ -L $HOME/.gitconfig ]]; then
        if [[ -f $HOME/.gitconfig ]]; then
            rm -f $HOME/.gitconfig
        fi
        ln -s $GIT_VOLUME/gitconfig $HOME/.gitconfig
    fi
fi
